protoc --go_opt=paths=source_relative --go_out=./  auth/auth.proto
protoc --go_opt=paths=source_relative --go_out=./  conversation/conversation.proto
protoc --go_opt=paths=source_relative --go_out=./  errinfo/errinfo.proto
protoc --go_opt=paths=source_relative --go_out=./  friend/friend.proto
protoc --go_opt=paths=source_relative --go_out=./  group/group.proto
protoc --go_opt=paths=source_relative --go_out=./  msg/msgv3.proto
protoc --go_opt=paths=source_relative --go_out=./  msggateway/msggateway.proto
protoc --go_opt=paths=source_relative --go_out=./  push/push.proto
protoc --go_opt=paths=source_relative --go_out=./  rtc/rtc.proto
protoc --go_opt=paths=source_relative --go_out=./  sdkws/sdkws.proto
protoc --go_opt=paths=source_relative --go_out=./  third/third.proto
protoc --go_opt=paths=source_relative --go_out=./  user/user.proto
protoc --go_opt=paths=source_relative --go_out=./  wrapperspb/wrapperspb.proto
protoc --go_opt=paths=source_relative --go_out=./  statistics/statistics.proto